# Vault network interface (stable contract)
vault_api_port: 8200
vault_cluster_port: 8201
vault_consul_port: 8500

vault_api_health_path: /v1/sys/health

vault_consul_hosts: "{{ groups['consul'] | default([]) }}"
vault_consul_bootstrap_host: "{{ vault_consul_hosts | first }}"