consul_version: "1.22.2"

consul_user: consul
consul_group: consul

consul_data_dir: /opt/consul
consul_config_dir: /etc/consul.d

# Ansible fact for the default IPv4 address of the host
consul_bind_addr: "{{ ansible_default_ipv4.address }}"
consul_client_addr: "{{ ansible_default_ipv4.address }}"
consul_advertise_addr: "{{ ansible_default_ipv4.address }}"

consul_log_level: INFO


consul_tls_dir: /etc/consul.d/tls