vault_version: "1.21.2"

vault_user: vault
vault_group: vault

vault_data_dir: /opt/vault/data
vault_config_dir: /etc/vault.d
vault_install_dir: /usr/local/bin
vault_binary_path: "{{ vault_install_dir }}/vault"


vault_consul_path: "vault/"


vault_tls_dir: "{{ vault_config_dir }}/tls"
